production_url: https://apsdehal.in
permalink: /blog/:title
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    math_engine: mathjax
# rss
title: Amanpreet Singh
description: Development and Views Blog
